<div class="style form">
<h2>Log In</h2>
<form action="index.php?route=login" method="POST">
    <label for="email">Email</label>
    <input type="email" id="email" name="email">
    <label for="password">Password</label>
    <input type="password" id="password" name="password">
    <input type="submit" value="LogIn">
    <span class="advert"><?php
    if(isset($this->data["message"]))
    {
        echo $this->data["message"];
    }
    ?></span>
</form>
</div>
